version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: nginx-fpm-mysql-supervisord-alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
    ports:
      - "8088:8080"