version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: php-nginx-supervisor-alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
      - /app/vendor
      - ./etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/docker/php/www.conf:/usr/local/etc/php-fpm.conf
      - ./etc/docker/supervisor/supervisord.conf:/etc/supervisord.conf
    ports:
      - "8086:8080"
    networks:
      - php-nginx-supervisor-alpine-elasticsearch-net

  # ELASTICSEARCH (APP)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch-php-nginx-supervisor-alpine
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /home/$USER/elasticsearch-php-nginx-supervisor-alpine/elasticsearch-data:/data/db
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - php-nginx-supervisor-alpine-elasticsearch-net

networks:
  php-nginx-supervisor-alpine-elasticsearch-net:      