
services:
  dbmysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbmysql
    tty: true
    platform: 'linux/x86_64'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306' # Exponiendo el puerto para conexiones externas
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'dbmysql_data:/var/lib/mysql' # Persistencia de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  dbmysql_data:

networks:
  default:
    driver: bridge
